/* =========================================================
   More of the archipelago to find: extra fish, bugs, plants and finds for the Islandex.
   Many are tied to when and where: `sea` (seasons, on your own island), `hr` ([from,to) hours, may wrap past midnight),
   `rain` (only in rain) and `dry` (never in rain), so the book fills over weeks rather than an afternoon.
   Finds with `tpl` are drawn from a template (22b-dexart) in their own colours; `forage` ones turn up on your island
   (by trees, `at:'tree'`, or in the grass) rather than washing up on beaches.
   ========================================================= */
// is this entry about right now? (the season part only applies on your own island, where the seasons are real)
function dexOk(e,isl){if(!e)return false;
  if(e.hr){const h=S.hour,[a,b]=e.hr;if(a<b?(h<a||h>=b):(h<a&&h>=b))return false;}
  if(e.sea&&isl&&isl.home&&!e.sea.includes(season()))return false;if(e.rain&&!S.rain)return false;if(e.dry&&S.rain)return false;return true;}
const SPR_SU=['spring','summer'],SU_AU=['summer','autumn'],AU=['autumn'],WI=['winter'],SP=['spring'],SU=['summer'],AU_WI=['autumn','winter'],WI_SP=['winter','spring'];

Object.assign(BUGS,{
  // your island, by day
  bumblebee:{name:'Bumblebee',price:70,w:18,time:'day',bio:['home','meadow'],sea:SPR_SU,col:'#f6c83a',dk:'#2b1e2e',small:1},
  orangetip:{name:'Orange-Tip',price:80,w:16,time:'day',bio:['home','meadow'],sea:SP,col:'#f4f0e6',dk:'#f08a2a'},
  brimstone:{name:'Brimstone',price:90,w:14,time:'day',bio:['home'],sea:SP,col:'#e8f080',dk:'#a8b040'},
  commonblue:{name:'Common Blue',price:70,w:18,time:'day',bio:['home','meadow'],sea:SU,col:'#7ab4ee',dk:'#3a64b0',small:1},
  peacock:{name:'Peacock Butterfly',price:180,w:10,time:'day',bio:['home','meadow'],sea:SU_AU,col:'#c8402a',dk:'#2a3a8a'},
  paintedlady:{name:'Painted Lady',price:120,w:12,time:'day',bio:['home','meadow'],sea:SU_AU,col:'#f0a060',dk:'#2b1e2e'},
  skipper:{name:'Small Skipper',price:60,w:18,time:'day',bio:['home'],sea:SU,col:'#e8a040',dk:'#8a5a2a',small:1},
  hairstreak:{name:'Purple Hairstreak',price:420,w:4,time:'day',bio:['home'],sea:SU,col:'#8a6ad0',dk:'#3a2a5a',small:1},
  clouded:{name:'Clouded Yellow',price:150,w:10,time:'day',bio:['home','meadow'],sea:AU,col:'#f6d04a',dk:'#8a6a2a'},
  comma:{name:'Comma',price:130,w:12,time:'day',bio:['home','autumn'],sea:AU,col:'#e08a3a',dk:'#5a3a2a'},
  mourning:{name:'Mourning Cloak',price:600,w:3,time:'day',bio:['home'],sea:WI_SP,col:'#5a3a3a',dk:'#f6e0a0'},
  hawkmoth:{name:'Hummingbird Hawk-Moth',price:350,w:6,time:'day',bio:['home'],sea:SU,col:'#8a7a6a',dk:'#e8903a',small:1},
  dewwing:{name:'Dewdrop Blue',price:280,w:7,time:'day',bio:['home'],hr:[5,8],col:'#bfe6ff',dk:'#6a9ad0',small:1},
  duskskipper:{name:'Dusk Skipper',price:260,w:7,time:'day',bio:['home'],hr:[17,20],col:'#d88a5a',dk:'#5a3a3a',small:1},
  grasshopper:{name:'Grasshopper',price:60,w:18,time:'day',bio:['home','meadow'],sea:SU_AU,kind:'crawl',col:'#7ab84a',dk:'#3d6e2c'},
  shieldbug:{name:'Shield Bug',price:80,w:14,time:'day',bio:['home'],sea:AU,kind:'crawl',col:'#5f9e3a',dk:'#2a4a1e'},
  caterpillar:{name:'Caterpillar',price:50,w:18,time:'day',bio:['home','meadow'],sea:SP,kind:'crawl',col:'#9fd060',dk:'#f6d04a'},
  woodant:{name:'Wood Ant',price:30,w:22,time:'day',bio:['home','pine'],kind:'crawl',col:'#8a3a2a',dk:'#2b1e2e'},
  pillbug:{name:'Pill Bug',price:40,w:20,time:'day',bio:['home'],kind:'crawl',col:'#8a8a9a',dk:'#4a4a5a'},
  snail:{name:'Garden Snail',price:90,w:18,time:'day',bio:['home','meadow'],rain:1,kind:'crawl',col:'#c8a878',dk:'#6a5030'},
  rainbeetle:{name:'Rain Beetle',price:240,w:8,time:'day',bio:['home'],rain:1,kind:'crawl',col:'#3a6a8a',dk:'#1a2a3a'},
  skater:{name:'Pond Skater',price:110,w:12,time:'day',bio:['home','swamp'],rain:1,kind:'drag',col:'#6a6a7a',dk:'#2a2a3a'},
  jewelbeetle:{name:'Jewel Beetle',price:700,w:3,time:'day',bio:['home','tropic'],sea:SU,kind:'crawl',col:'#3ad0a0',dk:'#1a6a5a'},
  goldscarab:{name:'Golden Scarab',price:2500,w:0.8,time:'day',bio:['home'],dry:1,kind:'crawl',col:'#f6c83a',dk:'#a87a1a',glow:1},
  darter:{name:'Red Darter',price:160,w:12,time:'day',bio:['home','meadow'],sea:SU_AU,kind:'drag',col:'#e0503a',dk:'#6a2a1e'},
  emperordrag:{name:'Emperor Dragonfly',price:320,w:6,time:'day',bio:['home'],sea:SU,kind:'drag',col:'#4ab0f0',dk:'#1e5a8a'},
  mayfly:{name:'Mayfly',price:150,w:10,time:'day',bio:['home','swamp'],sea:SP,hr:[5,9],kind:'drag',col:'#e8e0c0',dk:'#8a8060'},
  snowflea:{name:'Snow Flea',price:120,w:12,time:'day',bio:['home','snow'],sea:WI,kind:'crawl',col:'#6a7aa0',dk:'#2a3a5a',small:1},
  // your island, by night
  rosymaple:{name:'Rosy Maple Moth',price:260,w:9,time:'night',bio:['home'],sea:SU,col:'#f39ab0',dk:'#f6d04a'},
  tigermoth:{name:'Tiger Moth',price:200,w:10,time:'night',bio:['home','meadow'],sea:SU_AU,col:'#f0a040',dk:'#2b1e2e'},
  elephanthawk:{name:'Elephant Hawk-Moth',price:380,w:6,time:'night',bio:['home'],sea:SU,col:'#e890b0',dk:'#8aa05a'},
  owlet:{name:'Owlet Moth',price:90,w:18,time:'night',bio:['home','pine'],col:'#a89a88',dk:'#5a4a3a'},
  wintermoth:{name:'Winter Moth',price:160,w:12,time:'night',bio:['home','snow'],sea:WI,col:'#c8c0b0',dk:'#6a6058'},
  ghostmoth:{name:'Ghost Moth',price:900,w:2,time:'night',bio:['home'],hr:[23,3],col:'#f4f4ff',dk:'#b8c0e0',glow:1},
  mooncricket:{name:'Moon Cricket',price:180,w:10,time:'night',bio:['home','meadow'],sea:AU,kind:'crawl',col:'#6a8a4a',dk:'#2a3a1e'},
  starbeetle:{name:'Starlight Beetle',price:1200,w:1.5,time:'night',bio:['home'],dry:1,kind:'crawl',col:'#8ab0ff',dk:'#2a3a8a',glow:1},
  // the other islands
  glasswing:{name:'Glasswing',price:380,w:7,time:'day',bio:['tropic'],col:'#e8f4ff',dk:'#2b1e2e'},
  mantis:{name:'Orchid Mantis',price:1100,w:2,time:'day',bio:['tropic'],kind:'crawl',col:'#f8d0e8',dk:'#d890b8'},
  leafcutter:{name:'Leafcutter Ant',price:140,w:14,time:'day',bio:['tropic'],kind:'crawl',col:'#a85a2a',dk:'#5a2a1e'},
  sawyer:{name:'Pine Sawyer',price:300,w:8,time:'day',bio:['pine'],kind:'crawl',col:'#4a4038',dk:'#c8b8a0'},
  woodnymph:{name:'Wood Nymph',price:220,w:10,time:'day',bio:['pine','meadow'],col:'#8a6a4a',dk:'#f0e0a0'},
  scorpionfly:{name:'Snow Scorpionfly',price:420,w:6,time:'day',bio:['snow'],kind:'crawl',col:'#3a3040',dk:'#8a8aa0'},
  ashmoth:{name:'Ash Moth',price:280,w:9,time:'night',bio:['volcano'],col:'#9a9098',dk:'#4a4048'},
  magmabeetle:{name:'Magma Beetle',price:650,w:4,time:'day',bio:['volcano'],kind:'crawl',col:'#f06a2a',dk:'#3a1a14',glow:1},
  waterscorp:{name:'Water Scorpion',price:300,w:7,time:'day',bio:['swamp'],kind:'crawl',col:'#6a5a3a',dk:'#2a2014'},
  boghawker:{name:'Bog Hawker',price:360,w:6,time:'day',bio:['swamp'],kind:'drag',col:'#6ad08a',dk:'#1e5a3a'},
  weevil:{name:'Acorn Weevil',price:160,w:12,time:'day',bio:['autumn'],kind:'crawl',col:'#9a6a3a',dk:'#4a2e1e'},
  maplemoth:{name:'Maple Moth',price:240,w:9,time:'night',bio:['autumn'],col:'#e8703a',dk:'#8a2e1e'},
  meadowbrown:{name:'Meadow Brown',price:60,w:20,time:'day',bio:['meadow'],col:'#a8784a',dk:'#5a3a24'},
  marbled:{name:'Marbled White',price:130,w:12,time:'day',bio:['meadow'],col:'#f7f2e6',dk:'#2b1e2e'},
});

Object.assign(FISH,{
  // your island's river
  minnow:{name:'Minnow',price:25,w:32,size:1,hab:'river',bio:['home','meadow'],col:'#b8c0a8',dk:'#5a6a5a',fin:'#d0d8c0'},
  stickleback:{name:'Stickleback',price:40,w:24,size:1,hab:'river',bio:['home','meadow'],sea:SPR_SU,col:'#8ab070',dk:'#c84a3a',fin:'#a8c090'},
  loach:{name:'Stone Loach',price:60,w:18,size:1,hab:'river',bio:['home'],col:'#a89070',dk:'#5a4a3a',fin:'#c8b090',spr:'eel'},
  dace:{name:'Dace',price:70,w:18,size:2,hab:'river',bio:['home','pine'],col:'#c8d0d8',dk:'#6a7a8a',fin:'#e0e4ea'},
  chub:{name:'Chub',price:110,w:14,size:3,hab:'river',bio:['home','meadow'],col:'#a8a888',dk:'#4a4a3a',fin:'#d88a5a'},
  perch:{name:'Perch',price:120,w:12,size:2,hab:'river',bio:['home','swamp'],col:'#9ab060',dk:'#3a4a2a',fin:'#e8603a'},
  carp:{name:'Carp',price:140,w:12,size:4,hab:'river',bio:['home','swamp'],sea:SU_AU,col:'#b89a5a',dk:'#6a5030',fin:'#c8a060'},
  browntrout:{name:'Brown Trout',price:200,w:8,size:3,hab:'river',bio:['home','pine'],sea:['spring','autumn'],col:'#b89060',dk:'#5a3a24',fin:'#d8a878'},
  rivereel:{name:'River Eel',price:260,w:7,size:3,hab:'river',bio:['home','swamp'],time:'night',col:'#5a5a3a',dk:'#2a2a1e',fin:'#7a7a5a',spr:'eel'},
  goldcarp:{name:'Golden Carp',price:1400,w:1,size:3,hab:'river',bio:['home'],col:'#f6c83a',dk:'#c8852a',fin:'#fff0a0'},
  raintrout:{name:'Rain Trout',price:320,w:5,size:3,hab:'river',bio:['home','pine'],rain:1,col:'#a8c0e0',dk:'#4a6a9a',fin:'#e8a8b8'},
  // the sea round your island
  anchovy:{name:'Anchovy',price:30,w:30,size:1,hab:'any',bio:['home','open'],col:'#a8b8c8',dk:'#5a6a80',fin:'#c8d4e0'},
  herring:{name:'Herring',price:60,w:20,size:2,hab:'any',bio:['home','open'],sea:AU_WI,col:'#b8c8d8',dk:'#4a5a78',fin:'#d8e0ea'},
  seabass:{name:'Sea Bass',price:260,w:8,size:3,hab:'shore',bio:['home','open'],col:'#a8b0b8',dk:'#4a5058',fin:'#c8ccd0'},
  mullet:{name:'Grey Mullet',price:110,w:14,size:3,hab:'shore',bio:['home'],col:'#b0b4b8',dk:'#5a5e68',fin:'#d0d2d6'},
  pollock:{name:'Pollock',price:140,w:12,size:3,hab:'deep',bio:['home','open'],sea:AU_WI,col:'#8a9a78',dk:'#3a4a30',fin:'#b0b898'},
  plaice:{name:'Plaice',price:170,w:10,size:3,hab:'shore',bio:['home'],col:'#b89a78',dk:'#e07a3a',fin:'#c8b090',spr:'ray'},
  sole:{name:'Dover Sole',price:300,w:6,size:3,hab:'shore',bio:['home','open'],time:'night',col:'#a8906a',dk:'#5a4a30',fin:'#c8b090',spr:'ray'},
  wrasse:{name:'Ballan Wrasse',price:190,w:9,size:2,hab:'shore',bio:['home'],sea:SU,col:'#6ab08a',dk:'#2a5a4a',fin:'#e8a060'},
  blenny:{name:'Blenny',price:50,w:22,size:1,hab:'shore',bio:['home'],col:'#a8906a',dk:'#4a3a2a',fin:'#c8a878'},
  goby:{name:'Rock Goby',price:45,w:22,size:1,hab:'shore',bio:['home','tropic'],col:'#8a7a5a',dk:'#3a3024',fin:'#a89a78'},
  cuttlefish:{name:'Cuttlefish',price:340,w:6,size:3,hab:'shore',bio:['home','open'],sea:SPR_SU,col:'#c8a8a0',dk:'#6a4a4a',fin:'#e0c8c0',spr:'squid'},
  moonjelly:{name:'Moon Jelly',price:150,w:12,size:2,hab:'any',bio:['home','open'],sea:SU,col:'#e8e8ff',dk:'#b8a8e8',fin:'#f4f0ff',spr:'jelly'},
  sunfish:{name:'Ocean Sunfish',price:1600,w:1,size:6,hab:'deep',bio:['home','open'],sea:SU,col:'#b8c0c8',dk:'#6a7078',fin:'#d0d4d8',spr:'puffer'},
  lanternfish:{name:'Lanternfish',price:420,w:5,size:1,hab:'deep',bio:['home','open'],time:'night',col:'#4a5a8a',dk:'#1e2a4a',fin:'#8ab0ff'},
  ghostshark:{name:'Ghost Shark',price:1800,w:0.9,size:5,hab:'deep',bio:['open'],hr:[0,4],col:'#c8c8d8',dk:'#6a6a88',fin:'#e0e0f0'},
  dawnbream:{name:'Dawn Bream',price:380,w:5,size:2,hab:'any',bio:['home','open'],hr:[5,8],col:'#f4c8a8',dk:'#c86a5a',fin:'#ffe0c8'},
  duskray:{name:'Dusk Ray',price:520,w:3,size:4,hab:'deep',bio:['home','open'],hr:[18,21],col:'#8a6aa8',dk:'#3a2a5a',fin:'#b89ad8',spr:'ray'},
  barracuda:{name:'Barracuda',price:480,w:5,size:4,hab:'deep',bio:['open','tropic'],col:'#a8b8c8',dk:'#3a4a5a',fin:'#c8d0d8'},
  swordfish:{name:'Swordfish',price:2200,w:0.8,size:6,hab:'deep',bio:['open'],sea:SU,col:'#6a7a9a',dk:'#2a3a5a',fin:'#8a9ab8'},
  hammerhead:{name:'Hammerhead',price:2600,w:0.7,size:6,hab:'deep',bio:['open','tropic'],col:'#8a9098',dk:'#4a5058',fin:'#a8b0b8'},
  // the other islands' waters
  butterflyfish:{name:'Butterflyfish',price:220,w:10,size:1,hab:'shore',bio:['tropic'],col:'#f6d04a',dk:'#2b1e2e',fin:'#f7f2e6'},
  bluetang:{name:'Blue Tang',price:280,w:9,size:2,hab:'shore',bio:['tropic'],col:'#3a6ae0',dk:'#1a2a6a',fin:'#f6d04a'},
  lionfish:{name:'Lionfish',price:600,w:4,size:2,hab:'shore',bio:['tropic','volcano'],col:'#e8a080',dk:'#8a2a1e',fin:'#f7f2e6'},
  grouper:{name:'Grouper',price:500,w:5,size:5,hab:'deep',bio:['tropic','open'],col:'#8a7a5a',dk:'#3a3024',fin:'#a89a78'},
  trigger:{name:'Triggerfish',price:320,w:7,size:2,hab:'shore',bio:['tropic'],col:'#4a5a6a',dk:'#f6c83a',fin:'#8a9aaa'},
  bowfin:{name:'Bowfin',price:240,w:9,size:3,hab:'river',bio:['swamp'],col:'#6a7a4a',dk:'#2a3a1e',fin:'#8a9a60'},
  mudskipper:{name:'Mudskipper',price:180,w:11,size:1,hab:'river',bio:['swamp'],col:'#8a7a5a',dk:'#4a3a2a',fin:'#6ab0e0'},
  snakehead:{name:'Snakehead',price:420,w:5,size:4,hab:'river',bio:['swamp'],time:'night',col:'#5a5a3a',dk:'#2a2a1a',fin:'#7a7a4a',spr:'eel'},
  ashcarp:{name:'Ash Carp',price:360,w:7,size:3,hab:'river',bio:['volcano'],col:'#6a6068',dk:'#2a2428',fin:'#f6a040'},
  icecod:{name:'Ice Cod',price:300,w:8,size:3,hab:'deep',bio:['snow'],col:'#c8d8e8',dk:'#6a8aa8',fin:'#e8f0f8'},
  snowcrab:{name:'Snow Crab',price:520,w:5,size:2,hab:'shore',bio:['snow'],col:'#e8a080',dk:'#a85a3a',fin:'#f4c8a8',spr:'octo'},
  pinepike:{name:'Pine Pike',price:280,w:8,size:4,hab:'river',bio:['pine'],col:'#7a8a5a',dk:'#2a3a1e',fin:'#a8b070'},
  maplekoi:{name:'Maple Koi',price:650,w:3,size:3,hab:'river',bio:['autumn'],col:'#f4f0e8',dk:'#c8402a',fin:'#f0a060'},
  goldperch:{name:'Golden Perch',price:540,w:4,size:2,hab:'river',bio:['meadow','autumn'],col:'#f0c060',dk:'#8a5a2a',fin:'#f8e0a0'},
});

Object.assign(PLANTS,{
  buttercup:{name:'Buttercup',price:25,w:18,kind:'flower',bio:['meadow'],col:'#f6d04a',dk:'#c8952a',c:'#f7f2e6'},
  cornflower:{name:'Cornflower',price:45,w:14,kind:'flower',bio:['meadow'],col:'#5a8ae0',dk:'#3a5ab0',c:'#2b1e2e'},
  poppy:{name:'Poppy',price:50,w:14,kind:'flower',bio:['meadow','autumn'],col:'#e0403a',dk:'#962a2e',c:'#2b1e2e'},
  foxglove:{name:'Foxglove',price:90,w:10,kind:'flower',bio:['meadow','pine'],col:'#c878c8',dk:'#8a3a8a',c:'#f7f2e6'},
  eveprimrose:{name:'Evening Primrose',price:140,w:8,kind:'flower',bio:['meadow'],time:'night',col:'#fff08a',dk:'#c8b040',c:'#f7f2e6'},
  raspberry:{name:'Wild Raspberry',price:60,w:14,kind:'berry',bio:['meadow','pine'],col:'#e0405a',dk:'#8a2a3a'},
  plumeria:{name:'Plumeria',price:80,w:12,kind:'flower',bio:['tropic'],col:'#fff4e0',dk:'#f6c83a',c:'#f6d04a'},
  birdparadise:{name:'Bird of Paradise',price:320,w:5,kind:'flower',bio:['tropic'],col:'#f08a2a',dk:'#3a6ae0',c:'#f7f2e6'},
  mango:{name:'Wild Mango',price:140,w:9,kind:'fruit',bio:['tropic'],col:'#f0a040',dk:'#c8602a'},
  passionfruit:{name:'Passion Fruit',price:120,w:10,kind:'fruit',bio:['tropic'],col:'#8a3a8a',dk:'#5a2a5a'},
  bilberry:{name:'Bilberry',price:55,w:14,kind:'berry',bio:['pine'],col:'#4a4ab0',dk:'#2a2a6a'},
  hedgehogshroom:{name:'Hedgehog Mushroom',price:150,w:8,kind:'mushroom',bio:['pine','autumn'],col:'#f6b040',dk:'#c8802a'},
  porcini:{name:'Porcini',price:220,w:6,kind:'mushroom',bio:['pine','autumn'],col:'#8a5a3a',dk:'#5a3a24'},
  twinflower:{name:'Twinflower',price:110,w:9,kind:'flower',bio:['pine'],col:'#f8c8d8',dk:'#c88aa8',c:'#f7f2e6'},
  hawthorn:{name:'Hawthorn Berry',price:60,w:14,kind:'berry',bio:['autumn'],col:'#c8302a',dk:'#7a1e1a'},
  aster:{name:'Aster',price:70,w:12,kind:'flower',bio:['autumn'],col:'#a88ae0',dk:'#6a4ab0',c:'#f6d04a'},
  pumpkin:{name:'Wild Gourd',price:180,w:7,kind:'ground',bio:['autumn'],col:'#f08a2a',dk:'#a8501e'},
  snowbell:{name:'Snowbell',price:90,w:12,kind:'flower',bio:['snow'],col:'#f7f7ff',dk:'#b8c8d8',c:'#9fd060'},
  winterberry:{name:'Winterberry',price:80,w:12,kind:'berry',bio:['snow'],col:'#e0303a',dk:'#8a1e24'},
  frostcap:{name:'Frost Cap',price:260,w:5,kind:'mushroom',bio:['snow'],col:'#c8e8ff',dk:'#6a9ad0'},
  edelweiss:{name:'Edelweiss',price:600,w:2.5,kind:'flower',bio:['snow'],col:'#f7f7f0',dk:'#c8c8b8',c:'#f6d04a'},
  fireweed:{name:'Fireweed',price:90,w:12,kind:'flower',bio:['volcano'],col:'#e84a8a',dk:'#a02a5a',c:'#f7f2e6'},
  ashbloom:{name:'Ash Bloom',price:300,w:5,kind:'flower',bio:['volcano'],col:'#c8c0c8',dk:'#6a606a',c:'#f6a040'},
  emberberry:{name:'Ember Berry',price:240,w:6,kind:'berry',bio:['volcano'],col:'#f6602a',dk:'#a02a1e'},
  pitcher:{name:'Pitcher Plant',price:280,w:6,kind:'ground',bio:['swamp'],col:'#8ab04a',dk:'#a8302a'},
  marshmarigold:{name:'Marsh Marigold',price:70,w:13,kind:'flower',bio:['swamp'],col:'#f6d04a',dk:'#a8852a',c:'#5f9e3a'},
  bogcotton:{name:'Bog Cotton',price:60,w:14,kind:'flower',bio:['swamp'],col:'#fbfbf4',dk:'#c8c8b8',c:'#9a9a8a'},
  moonorchid:{name:'Moon Orchid',price:1400,w:1,kind:'flower',bio:['swamp','tropic'],time:'night',col:'#f4f8ff',dk:'#c8d8e8',c:'#bfe6ff',glow:1},
  moonflower:{name:'Moonflower',price:800,w:1.8,kind:'flower',bio:['meadow','tropic'],time:'night',col:'#f0f4ff',dk:'#b8c8f0',c:'#fff4b0',glow:1},
  starfruit:{name:'Starfruit',price:200,w:7,kind:'fruit',bio:['tropic'],col:'#f6e060',dk:'#c8a82a'},
});

Object.assign(FINDS,{
  // washed up on beaches
  cowrie:{name:'Cowrie',price:40,w:16,bio:['any'],tpl:'shell',col:'#f4e8d8',dk:'#b89a78'},
  scallop:{name:'Scallop',price:50,w:14,bio:['any'],tpl:'fan',col:'#f0a878',dk:'#c86a4a'},
  whelk:{name:'Whelk',price:55,w:12,bio:['any'],tpl:'spiral',col:'#e8d8c0',dk:'#9a7a5a'},
  moonsnail:{name:'Moon Snail',price:90,w:8,bio:['any'],tpl:'spiral',col:'#d8c8e0',dk:'#8a7aa0'},
  mussel:{name:'Blue Mussel',price:30,w:18,bio:['any'],tpl:'shell',col:'#3a4a7a',dk:'#1e2a4a'},
  urchin:{name:'Urchin Test',price:120,w:6,bio:['any'],tpl:'stone',col:'#c8a8d8',dk:'#8a6aa0'},
  mermaidpurse:{name:"Mermaid's Purse",price:150,w:5,bio:['any'],tpl:'leaf',col:'#3a3024',dk:'#1e1a14'},
  kelp:{name:'Kelp',price:10,w:22,bio:['any'],tpl:'leaf',col:'#5a8a3a',dk:'#2a4a1e'},
  agate:{name:'Beach Agate',price:180,w:5,bio:['any'],tpl:'gem',col:'#e8a870',dk:'#a85a3a'},
  jasper:{name:'Red Jasper',price:160,w:5,bio:['any'],tpl:'stone',col:'#c8503a',dk:'#7a2a1e'},
  marble:{name:'Glass Marble',price:220,w:3,bio:['any'],tpl:'gem',col:'#8ad0e8',dk:'#3a8aa8'},
  button:{name:'Old Brass Button',price:140,w:4,bio:['any'],tpl:'coin',col:'#d8b050',dk:'#8a6a2a'},
  sharktooth:{name:'Shark Tooth',price:400,w:1.8,bio:['any'],tpl:'tooth',col:'#f4f0e0',dk:'#a8a08a'},
  whalebone:{name:'Whale Bone',price:900,w:0.8,bio:['any'],tpl:'bone',col:'#f0e8d8',dk:'#b8a888'},
  gullfeather:{name:'Gull Feather',price:20,w:14,bio:['any'],tpl:'feather',col:'#f4f4f4',dk:'#8a8a9a'},
  nautilus:{name:'Nautilus Shell',price:1100,w:0.8,bio:['any'],tpl:'spiral',col:'#f4e0c8',dk:'#c8703a'},
  pumice:{name:'Pumice',price:60,w:12,bio:['volcano'],tpl:'stone',col:'#c8c0b8',dk:'#8a8078'},
  snowquartz:{name:'Snow Quartz',price:200,w:6,bio:['snow'],tpl:'gem',col:'#f4f8ff',dk:'#a8b8d0'},
  coralbranch:{name:'Pink Coral',price:180,w:6,bio:['tropic'],tpl:'leaf',col:'#f39ab0',dk:'#c8607a'},
  bogoak:{name:'Bog Oak',price:240,w:5,bio:['swamp'],tpl:'bone',col:'#4a3a2a',dk:'#2a2014'},
  // found on your island, by trees and in the grass
  chestnut:{name:'Sweet Chestnut',price:60,w:0,bio:['wild'],tpl:'nut',col:'#8a4a2a',dk:'#4a2a1e',forage:1,at:'tree',sea:AU},
  hazelnut:{name:'Hazelnut',price:45,w:0,bio:['wild'],tpl:'nut',col:'#b8804a',dk:'#6a4a2a',forage:1,at:'tree',sea:AU},
  mapleleaf:{name:'Maple Leaf',price:15,w:0,bio:['wild'],tpl:'leaf',col:'#e8603a',dk:'#a02a1e',forage:1,at:'tree',sea:AU},
  goldleaf:{name:'Golden Leaf',price:350,w:0,bio:['wild'],tpl:'leaf',col:'#f6c83a',dk:'#c8852a',forage:1,at:'tree',sea:AU,rare:1},
  morel:{name:'Morel',price:180,w:0,bio:['wild'],tpl:'cap',col:'#b89a6a',dk:'#6a5030',forage:1,at:'tree',sea:SP},
  puffball:{name:'Puffball',price:70,w:0,bio:['wild'],tpl:'cap',col:'#f4f0e0',dk:'#c8c0a8',forage:1,sea:SU_AU},
  chanterhome:{name:'Golden Chanterelle',price:160,w:0,bio:['wild'],tpl:'cap',col:'#f6b040',dk:'#c8802a',forage:1,at:'tree',sea:AU,rain:1},
  wildgarlic:{name:'Wild Garlic',price:40,w:0,bio:['wild'],tpl:'leaf',col:'#6ab84a',dk:'#3d6e2c',forage:1,at:'tree',sea:SP},
  robinegg:{name:'Robin Egg',price:500,w:0,bio:['wild'],tpl:'egg',col:'#9ad8e8',dk:'#5a9ab0',forage:1,at:'tree',sea:SP,rare:1},
  owlfeather:{name:'Owl Feather',price:220,w:0,bio:['wild'],tpl:'feather',col:'#c8a878',dk:'#6a5030',forage:1,at:'tree',hr:[20,6],rare:1},
  jayfeather:{name:'Jay Feather',price:120,w:0,bio:['wild'],tpl:'feather',col:'#5a8ae0',dk:'#2b1e2e',forage:1,at:'tree'},
  snailshell:{name:'Snail Shell',price:30,w:0,bio:['wild'],tpl:'spiral',col:'#e0c8a0',dk:'#8a6a4a',forage:1,rain:1},
  hollyberry:{name:'Holly Sprig',price:80,w:0,bio:['wild'],tpl:'leaf',col:'#2a6a3a',dk:'#c8302a',forage:1,at:'tree',sea:WI},
  icicle:{name:'Icicle',price:60,w:0,bio:['wild'],tpl:'tooth',col:'#dcf0ff',dk:'#8ab8e0',forage:1,at:'tree',sea:WI},
  dewpearl:{name:'Dew Pearl',price:450,w:0,bio:['wild'],tpl:'gem',col:'#e8fbff',dk:'#8ac8e0',forage:1,hr:[5,8],rare:1},
  arrowhead:{name:'Flint Arrowhead',price:600,w:0,bio:['wild'],tpl:'stone',col:'#6a6a78',dk:'#2a2a3a',forage:1,rare:1},
  // foraged on the other islands (85d-ecosys: each kind of island has its own), or left behind by the wildlife you watch
  honeycomb:{name:'Honeycomb',price:90,w:0,bio:['meadow','bloom','candy'],tpl:'stone',col:'#f6c040',dk:'#c0801e',eco:1},
  larkegg:{name:'Skylark Egg',price:320,w:0,bio:['meadow'],tpl:'egg',col:'#e8dcc0',dk:'#a8906a',eco:1,rare:1},
  mango:{name:'Wild Mango',price:80,w:0,bio:['tropic'],tpl:'egg',col:'#f6a83a',dk:'#d0602a',eco:1},
  parrotfeather:{name:'Parrot Feather',price:140,w:0,bio:['tropic'],tpl:'feather',col:'#e8402a',dk:'#2a6ae0',eco:1},
  seabean:{name:'Sea Bean',price:70,w:0,bio:['tropic','coral'],tpl:'nut',col:'#8a3a2a',dk:'#4a1e14',eco:1},
  lingonberry:{name:'Lingonberries',price:45,w:0,bio:['pine'],tpl:'nut',col:'#d8303a',dk:'#8a1a24',eco:1},
  snowberry:{name:'Snowberries',price:50,w:0,bio:['snow'],tpl:'nut',col:'#f4f8ff',dk:'#a8b8d0',eco:1},
  snowfeather:{name:'Ptarmigan Feather',price:110,w:0,bio:['snow'],tpl:'feather',col:'#f8f8ff',dk:'#9aa4b8',eco:1},
  sulfur:{name:'Sulfur Crystal',price:130,w:0,bio:['volcano'],tpl:'gem',col:'#f6e040',dk:'#b8a020',eco:1},
  firepepper:{name:'Fire Pepper',price:90,w:0,bio:['volcano'],tpl:'tooth',col:'#e8402a',dk:'#8a1a14',eco:1},
  bogmyrtle:{name:'Bog Myrtle',price:55,w:0,bio:['swamp'],tpl:'leaf',col:'#6a9a5a',dk:'#3a5a30',eco:1},
  heronfeather:{name:'Heron Feather',price:150,w:0,bio:['swamp'],tpl:'feather',col:'#a8b8c8',dk:'#4a5a6a',eco:1},
  prismshard:{name:'Prism Shard',price:180,w:0,bio:['crystal'],tpl:'gem',col:'#e8a8f0',dk:'#7a6ad0',eco:1},
  glowspore:{name:'Glowspore Cap',price:120,w:0,bio:['shroom'],tpl:'cap',col:'#b080f0',dk:'#6a40b0',eco:1},
  wildgumdrop:{name:'Wild Gumdrop',price:60,w:0,bio:['candy'],tpl:'egg',col:'#f070a0',dk:'#b03a6a',eco:1},
  peppermint:{name:'Peppermint Drop',price:70,w:0,bio:['candy'],tpl:'coin',col:'#f4f4f4',dk:'#e0303a',eco:1},
  rosepetal:{name:'Giant Petal',price:60,w:0,bio:['bloom'],tpl:'leaf',col:'#f8a0c0',dk:'#c8607a',eco:1},
  nectar:{name:'Nectar Drop',price:110,w:0,bio:['bloom'],tpl:'gem',col:'#f6d050',dk:'#d8902a',eco:1},
  pinkpearl:{name:'Pink Pearl',price:900,w:0,bio:['coral'],tpl:'gem',col:'#f8c0d0',dk:'#c87a90',eco:1,rare:1},
  glowpebble:{name:'Glow Pebble',price:120,w:0,bio:['neon'],tpl:'stone',col:'#60f0e8',dk:'#2a8aa0',eco:1},
  voltberry:{name:'Volt Berries',price:95,w:0,bio:['neon'],tpl:'nut',col:'#c060ff',dk:'#6a20b0',eco:1},
  antler:{name:'Shed Antler',price:380,w:0,bio:[],tpl:'bone',col:'#d8c8a8',dk:'#8a7a5a',eco:1,how:'left behind by a deer you watched'},
  scute:{name:'Turtle Scute',price:240,w:0,bio:[],tpl:'shell',col:'#8aa05a',dk:'#4a5a2a',eco:1,how:'left behind by a turtle you watched'},
  duckfeather:{name:'Mallard Feather',price:90,w:0,bio:[],tpl:'feather',col:'#3a8a5a',dk:'#1e4a3a',eco:1,how:'left behind by a duck you watched'},
});
// forage finds you could come across right now, for forageSpawn (77-forage)
const FORAGE_EXTRA=Object.keys(FINDS).filter(k=>FINDS[k].forage);
