/* =========================================================
   Debug / test API — only when the page is opened with ?debug
   Used by tools/smoke.mjs; handy from the browser console too (window.DS).
   ========================================================= */
if(/[?&]debug\b/.test(location.search)){
  const tileKeys=()=>islands[0].grass.map(([x,z])=>[x,z]);
  window.DS={
    state:()=>({day:S.day,hour:S.hour,shells:S.shells,sea:S.sea,loc:locName(),tiles:Object.keys(S.tiles).length,inv:{...S.inv},store:{...S.store},
      islands:islands.length,town:TOWN.name,buildings:TOWN.bld.filter(b=>!b.locked).map(b=>b.t),npcs:npcs.map(n=>n.name+' ('+n.pers+' '+n.sp+', '+n.state+(n.act?':'+n.act.k:'')+')'),px:PX,perfPx:PERF.px,inside:inside?inside.title:null}),
    hour:h=>{setHour(h);applyTime();},pix:()=>Object.entries(PIX),wx:k=>{if(k)setWx(k);return{wx:S.wx,next:S.wxNext,rain:S.rain,grey:wxGrey()};},wxStats:(n=400)=>{const o={};for(const se of ['spring','summer','autumn','winter']){S.seasonOv=se;const c={};let p=null;for(let i=0;i<n;i++){p=rollWx(p);c[p]=(c[p]||0)+1;}o[se]=c;}delete S.seasonOv;return o;},outpost:()=>S.outpost,catchNow:id=>{const tg={fish:id,g:new T.Group(),gold:false,x:vil.x+1.5,z:vil.z};shadows.push(tg);fishing={px:vil.x+1.5,pz:vil.z,state:'bite',t:0,target:tg};catchFish();return !!caught;},fish3d:(ks,sz=200)=>(ks==='all'?Object.keys(FISH):ks).map(k=>{const w=new T.Group(),m=fishModel(FISH[k]);m.rotation.y=Math.PI*0.75;w.add(m);return[k,snapThumb(w,sz)];}),scan:v=>{S.scan=v;applyFx();},fx:k=>{setFx(k);if(S.rain)stopRain();return Object.keys(FXS);},
    icons:(ks)=>{if(ks==='all')ks=[...Object.keys(FISH).map(k=>'f:'+k),...Object.keys(BUGS).map(k=>'b:'+k),...Object.keys(PLANTS).map(k=>'p:'+k),...Object.keys(FINDS).map(k=>'g:'+k),...CROP_IDS,'m:wood','m:stone','m:fiber','x:fert','x:bait','shell'];return ks.map(k=>[k,ICON[k]]);},
    fillBag:(n=4)=>{const pick=(o,pre)=>Object.keys(o).slice(0,n).map(k=>pre+k);for(const k of [...pick(FISH,'f:'),...pick(BUGS,'b:'),...pick(PLANTS,'p:'),...pick(FINDS,'g:'),'m:wood','m:stone','m:fiber','x:bait','x:fert',...CROP_IDS.slice(0,n*2).map(k=>k+'|normal'),CROP_IDS[3]+'|golden',CROP_IDS[6]+'|rainbow'])S.inv[k]=(S.inv[k]||0)+3;for(const k of ['bench','lamppost','picnic','parasol','fountain','brick','topiary','swing'])S.store[k]=2;updateHUD();return Object.keys(S.inv).length;},
    floorTest:()=>{S.store.brick=3;S.store.chair=1;startPlace('brick',true);const [x,z]=[placing.x,placing.z];layFloorAt(x,z);const second=nearestValid(x,z,'brick');if(second)layFloorAt(...second);endPlace();
      startPlace('chair',true);moveGhost(x,z);const ok=canPlace(x,z);if(ok)doPlace();endPlace();return{floor:!!floorAt(x,z)&&floorAt(x,z).k,obj:objAt(x,z)&&objAt(x,z).k,second:!!second&&!!floorAt(...second),left:S.store.brick||0,grassHidden:!!floorAt(x,z)};},
    map:(r=40)=>{const rows=[];for(let z=-r;z<=r;z++){let l='';for(let x=-r;x<=r;x++){const k=K(x,z),t=landMap.get(k),lv=lvlMap.get(k)||0,d=S.debris.find(q=>q.x===x&&q.z===z);
      l+=t==='bridge'?'=':riverSurf.has(k)?'~':!t?' ':t==='sand'?'.':t==='bridge'?'=':x===DOCK.x&&z===DOCK.z?'D':d&&d.k==='tree'?'T':t!=='grass'?t[0]:lv?String(lv):islMap.get(k)===0?',':'?';}rows.push(String(z).padStart(4)+' '+l.replace(/\s+$/,''));}return rows.join('\n');},
    cand:c=>{buildCandidate(c);return DS.map();},thumbs:(ks,sz=160)=>ks.map(k=>snapThumb(objGroup(k,ks.indexOf(k)+3,0.5),sz)),
    jr:()=>S.jr,loadDream:()=>setTimeout(loadDream,50),loadAcorn:()=>setTimeout(loadAcornfield,50),basics:()=>{const m=new Map();scene.children.forEach(o=>{if(o.isMesh&&o.material.type==='MeshBasicMaterial'&&o.visible){const k=(o.geometry.type||'')+':'+(o.geometry.attributes.position.count);m.set(k,(m.get(k)||0)+1);}});return[...m];},islMeshes:id=>{const out=[];islands[id].group.traverse(o=>{if(!(o.isMesh||o.isInstancedMesh))return;const g=o.geometry,t=(g.index?g.index.count:g.attributes.position.count)/3*(o.isInstancedMesh?o.count:1);out.push([o.isInstancedMesh?'I'+o.count:'M',o.material.type,Math.round(t),o.visible?1:0,o.castShadow?1:0,o.userData.tag||'']);});return out;},tillPatch:(w,h,water)=>{const r=DS.freeRow(w);if(!r)return null;let n=0;for(let j=0;j<h;j++)for(let i=0;i<w;i++){const x=r[0]+i,z=r[1]+j;if(canTill(x,z)){S.tiles[K(x,z)]={w:water&&i<w/2?1:0,crop:null};n++;}}rebuildSoil();DS.tp(r[0]+w/2,r[1]-1.5);return[r,n];},fishRow:(list,dx,dz)=>{list.forEach((k,i)=>spawnShadowAt(vil.x+dx*(2+i*0)+(-dz)*(i-list.length/2)*1.3,vil.z+dz*(2.5)+dx*(i-list.length/2)*1.3,k,0));return shadows.length;},shadowInfo:()=>shadows.map(s=>[s.fish,+s.v.toFixed(2),+s.x.toFixed(2),+s.z.toFixed(2)]),trader:()=>({shown:trader.shown,come:trader.come,x:trader.x,z:trader.z,stock:traderStock().map(q=>stockInfo(q).name+' '+q.price)}),traderOpen:()=>{traderHello();openSheet('trader','buy');},crateOpen:()=>openSheet('bag','all','crate'),crate:()=>S.crate,campCheck:()=>{const {x,z}=S.homeAt,ts=campTiles(x,z);return{home:[x,z],heart:S.heartAt&&[S.heartAt.x,S.heartAt.z],clash:ts.filter(([a,b])=>debrisAt(a,b)).length,treesNear:S.debris.filter(d=>d.k==='tree'&&ts.some(([a,b])=>Math.abs(a-d.x)<=1&&Math.abs(b-d.z)<=1)).length,heartInCamp:!!S.heartAt&&ts.some(([a,b])=>Math.abs(a-S.heartAt.x)<=1&&Math.abs(b-S.heartAt.z)<=1)};},breakCamp:()=>{const {x,z}=S.homeAt;S.heartAt={x:x-1,z:z+2};S.debris.push({x:x+2,z:z+1,k:'tree',v:0,r:0,hp:5});save();},tideTurn:low=>tideTurn(low,low?curIsl():null,false),sleep:()=>sleep(),tideInfo:()=>({next:tideNext(),today:lowTimes(0),tmw:lowTimes(1)}),rays:()=>({k:rayK,on:rays.filter(r=>r.a>0.05).map(r=>[+r.x.toFixed(1),+r.z.toFixed(1),+r.a.toFixed(2)]),cam:[cam.tx,cam.tz]}),falls:()=>falls.map(f=>[+f.a.toFixed(2),f.hit]),fell:()=>{const d=S.debris.filter(q=>q.k==='tree').sort((a,b)=>Math.hypot(a.x-vil.x,a.z-vil.z)-Math.hypot(b.x-vil.x,b.z-vil.z))[0];d.hp=1;S.tool='axe';showHeld();villager.rotation.y=Math.atan2(d.x-vil.x,d.z-vil.z);swingTool(()=>hitDebris(d));return[d.x,d.z];},digHere:()=>{const x=Math.round(vil.x),z=Math.round(vil.z)-1;S.tool='shovel';showHeld();villager.rotation.y=Math.PI;swingTool(()=>{digStab(x,z,0.6);swingTool(()=>digStab(x,z,1));});return[x,z];},pitch:()=>pitch&&{t:pitch.t,sy:pitch.sy,step:pitch.step,end:pitch.end},gain:(k,n=1)=>gain(k,n),campfire:()=>campfire(),tent:()=>S.home&&S.home.tent,resting:()=>!!rest,
    tp:(x,z)=>{S.sea=false;vil.x=vil.tx=x;vil.z=vil.tz=z;vil.path=null;cam.tx=x;cam.tz=z;},
    visit:id=>{const i=islands[id];S.disc[id]=1;const sp=(i.spots&&i.spots[1])||i.grass[0];DS.tp(sp[0]+0.6,sp[1]+0.6);},
    islands:()=>islands.map(i=>({id:i.id,biome:i.biome,name:i.name,x:i.cx,z:i.cz,r:Math.round(islR(i)),grand:!!i.grand,river:(i.rtiles||[]).length})),
    screen:(x,z)=>toScreen(x,topY(x,z),z),
    npcScreen:i=>{const n=npcs[i];return toScreen(n.x,n.y+0.5,n.z);},
    frLog:()=>frBuild.log||[],frSail:(x,z)=>{sailTo(x,z);return !!sail;},frBoat:()=>S.boat&&[Math.round(S.boat.x),Math.round(S.boat.z),!!sail],
    frInfo:()=>{const fr=islands.filter(i=>i.fr);return{R0:frR0,cells:frSeen.size,front:(S.front||[]).length,islands:fr.length,built:fr.filter(i=>i.group).length,lastMs:+(frBuild.ms||0).toFixed(1),tier:frTierAt(...frPos()),styles:fr.reduce((o,i)=>(o[i.style||i.biome]=(o[i.style||i.biome]||0)+1,o),{})};},
    // put the boat out at sea, d tiles past the charted world at angle a, and stream the islands round it
    frGo:(d,a=0.7)=>{const r=frR0+d,x=Math.cos(a)*r,z=Math.sin(a)*r;sail=null;S.sea=true;S.boat={x,z,r:0};vil.x=vil.tx=x;vil.z=vil.tz=z;cam.tx=x;cam.tz=z;introCam=null;frStream(true);const q=seaNear(Math.round(x),Math.round(z));if(q){S.boat.x=vil.x=vil.tx=cam.tx=q[0];S.boat.z=vil.z=vil.tz=cam.tz=q[1];}cullIslands();return DS.frInfo();},
    // find (rolling cells outward if need be) an island of a style, sail up beside it and look at it
    frVisit:(st,dist=18,yaw=0.6,pitch)=>{let isl=islands.find(i=>i.fr&&(i.style||i.biome)===st);
      for(let r=1;!isl&&r<40;r++)for(let a=0;a<24&&!isl;a++){const d=frR0+r*FR_C*0.8,x=Math.cos(a/24*6.283)*d,z=Math.sin(a/24*6.283)*d;frAddCell(Math.round(x/FR_C)+','+Math.round(z/FR_C),true);isl=islands.find(i=>i.fr&&(i.style||i.biome)===st);}
      if(!isl)return null;sail=null;S.sea=true;S.boat={x:isl.cx+isl.ext+3,z:isl.cz,r:0};vil.x=vil.tx=S.boat.x;vil.z=vil.tz=S.boat.z;frStream(true);if(!isl.group)frBuild(isl);cullIslands();
      {let best=null,bd=1e9;for(const [x,z] of isl.grass){const d=Math.hypot(x-isl.cx,z-isl.cz);if(d<bd){bd=d;best=[x,z];}}if(best){S.sea=false;vil.x=vil.tx=best[0];vil.z=vil.tz=best[1];vil.path=null;}}
      introCam=null;cam.tx=vil.x;cam.tz=vil.z;cam.yaw=yaw;cam.dist=dist;if(pitch)cam.pitch=pitch;return{id:isl.id,name:isl.name,kind:islKind(isl),r:+isl.r.toFixed(1),mode:isl.mode,tiers:isl.tiers,hole:isl.hole,ms:+(frBuild.ms||0).toFixed(1)};},
    frRebuild:(n=8,ids)=>{const out=[];for(const isl of ids?ids.map(i=>islands[i]):islands.filter(i=>i.fr&&i.group).slice(0,n)){if(!isl.group)frBuild(isl);frDrop(isl);const t=performance.now();frBuild(isl);out.push([isl.name,+isl.r.toFixed(1),Math.round(performance.now()-t),isl.keys.length]);}return out;},
    frIsl:id=>{const i=islands[id];return{built:!!i.group,vis:i.group&&i.group.visible,bob:(i.bob||[]).map(w=>({vis:w.visible,mv:w.children[0].visible,n:w.children[0].geometry.attributes.position.count,bb:w.children[0].geometry.boundingBox})),kids:i.group&&i.group.children.length,cx:i.cx,cz:i.cz};},
    decoOpen:()=>{decoOpen();return!!deco;},decoTab:(t,s)=>{deco.tab=t;if(s)deco.sub=s;renderDeco();},decoBuy:k=>{S.shells+=RI[k].cost;decoBuy(k);return deco.sel;},decoLook:(t,id)=>{const o=RLOOK[t][id];S.shells+=o.cost;decoLook(t,id);},decoAct:a=>decoAct(a),decoMove:(x,z,lv=0)=>{const it=S.room.find(i=>i.id===deco.sel);if(it)decoMoveTo(it,{x,z,lv});},
    cosy:()=>cosyScore(),rest:()=>[S.rest,S.day,restMul()],roomItems:()=>S.room.map(i=>[i.k,+i.x.toFixed(1),+i.z.toFixed(1),i.lv]),decoClose:()=>decoClose(),
    talk:i=>{const n=npcs[i];if(!n)return null;n.state='idle';n.path=null;n.act=null;const fa=n.face||0;vil.x=vil.tx=n.x+Math.sin(fa)*2.2;vil.z=vil.tz=n.z+Math.cos(fa)*2.2;vil.path=null;talkTo(n);return[n.name,n.pers,n.sp];},chatState:()=>chat&&{cur:chat.cur&&(chat.cur.txt||'').slice(0,60),kind:chat.cur&&Object.keys(chat.cur)[0],q:chat.q.length,shown:chat.shown},chatOcc:()=>{if(!chat)return null;const n=chat.n,mx=(vil.x+n.x)/2,mz=(vil.z+n.z)/2,y=cam.yaw+0.15,out=[];for(let t=0.9;t<13;t+=0.5){const x=Math.round(mx+Math.sin(y)*t),z=Math.round(mz+Math.cos(y)*t);const k=K(x,z),o=objAt(x,z),e=debMesh.get(k);out.push([t,x,z,occH(x,z),o&&o.k,e&&e.d&&e.d.k,TOWN.fixed.get(k),TOWN.res.get(k)]);}return{yw:chat.yw,yaw:cam.yaw,out:out.filter(r=>r[3]||r[4]||r[5]||r[6])};},chatRay:()=>{if(!chat)return null;const n=chat.n,o=camera.position.clone(),tg=new T.Vector3(n.x,n.y+0.5-curveDropFor(camera,n.x,n.z),n.z),dir=tg.clone().sub(o);const L=dir.length();dir.normalize();const rc=new T.Raycaster(o,dir,0,L-0.3);const h=rc.intersectObjects(scene.children,true).filter(q=>q.object.visible&&q.object!==villager&&!q.object.isPoints).slice(0,4);
      const who=q=>{let ob=q.object,path=[];while(ob&&path.length<5){path.push((ob.name||ob.type)+(ob.userData&&Object.keys(ob.userData).length?JSON.stringify(Object.keys(ob.userData)):''));ob=ob.parent;}return path.join('<');};return{cam:o.toArray().map(v=>+v.toFixed(1)),npc:[+n.x.toFixed(1),+n.z.toFixed(1)],me:[+vil.x.toFixed(1),+vil.z.toFixed(1)],hits:h.map(q=>[q.point.toArray().map(v=>+v.toFixed(1)),who(q)])};},chatTap:()=>chatTap(),chatPick:i=>chatPick(i),chatMenu:m=>chatMenu(m),
    roomProp:l=>{if(!inside)return null;const q=inside.room.props.find(p=>p.label===l||p.k===l);if(!q)return null;_pv.set(q.x,q.y-curveDropFor(roomCam,q.x,q.z),q.z).project(roomCam);return[(_pv.x+1)/2*innerWidth,(1-_pv.y)/2*innerHeight];},roomMe:()=>inside&&{x:+inside.x.toFixed(2),y:+(inside.y||0).toFixed(2),z:+inside.z.toFixed(2),lv:inside.lv,path:inside.path&&inside.path.length},
    findObj:k=>{const o=S.objs.filter(o=>o.k===k);return o.length?[o[0].x,o[0].z,o.length]:null;},
    hedgeRow:()=>{const at=DS.freeRow(5);if(!at)return null;const [x,z]=at;const put=(x,z)=>{if(!objAt(x,z))S.objs.push({id:S.nextId++,k:'hedge',x,z,r:0});};for(let i=0;i<5;i++)put(x+i,z);put(x+4,z-1);put(x+4,z-2);put(x,z-2);syncObjs();return at;},
    humanThumbs:(list,sz=200)=>list.map(h=>snapThumb(humanModel(h),sz)),charEd:()=>{openCharEd();return !!charEd;},charTab:t=>{charEd.tab=t;renderCharEd();},charSet:h=>setH(h),
    potGarden:()=>{const ks=POT_PLANTS.map(q=>'pot_'+q[0]),at=DS.freeRow(5);if(!at)return null;let i=0;for(let dz=0;dz<4&&i<ks.length;dz++)for(let dx=0;dx<5&&i<ks.length;dx++){const x=at[0]+dx,z=at[1]-dz;if(objAt(x,z))continue;S.objs.push({id:S.nextId++,k:ks[i++],x,z,r:0});}syncObjs();return at;},freeRow:(len=5)=>{for(const [x,z] of tileKeys()){let ok=true;for(let i=0;i<len&&ok;i++){const k=K(x+i,z);ok=canTill(x+i,z)&&farmQ(x+i,z)>1.3&&(lvlMap.get(k)||0)===(lvlMap.get(K(x,z))||0)&&!TOWN.bld.some(b=>Math.abs(b.x+0.5-(x+i))<4&&Math.abs(b.z+1-z)<4)&&!(S.boat&&Math.hypot(S.boat.x-(x+i),S.boat.z-z)<7);}if(ok)return[x,z];}return null;},
    give:(items)=>{Object.assign(S.inv,items||{'m:wood':14,'m:stone':11,'m:fiber':9,'g:shell':4,'f:sardine':2,'tomato|normal':3,'tomato|golden':1});updateHUD();},
    craft:i=>craft(i),sheet:(k,tab)=>openSheet(k,tab),closeSheet:()=>closeSheet(),
    enterHome:()=>enterHouse('home'),enterNpc:i=>{const n=npcs[i];enterHouse('vh',n.b,n);},leave:()=>leaveHouse(),
    // a demo row of crops (each id at growth p, 0..1) on free farm ground; returns the first tile
    farm:(ids,p=1,rows=1)=>{const r=DS.freeRow(ids.length);if(!r)return null;for(let j=0;j<rows;j++)ids.forEach((id,i)=>{const x=r[0]+i,z=r[1]+j,k=K(x,z);if(!S.tiles[k]&&!canTill(x,z))return;S.tiles[k]={w:1,crop:{t:id,p:Array.isArray(p)?p[j]:p,v:null,m:0}};});rebuildSoil();syncAllCrops();return r;},
    // drop sample models in a row for a close look: 'tree:bush', 'debris:bush', 'plant:blueberry', 'crop:tomato'
    specimen:(list,x,z)=>{list.forEach((w,i)=>{const [a,b]=w.split(':'),R=mulberry(i+7),X=x+i*1.3;let g;
      if(a==='tree')g=M(treeParts(b,R,0x9a9ea8));else if(a==='debris')g=M(debrisParts(b,R));else if(a==='plant')g=plantGroup(b,i+7);else{const c=cropParts(b,3,i+7);g=new T.Group();g.add(M(c.leaf));if(c.fruit.length)g.add(M(c.fruit));g.scale.setScalar(0.95);}
      g.position.set(X,topY(X,z),z);scene.add(g);});},
    // a text map of tiles: g grass, s sand, b bridge, r river, . sea; P town path, T tilled, O object, F fixed, D debris
    grid:(x0,z0,x1,z1)=>{const out=[];for(let z=z0;z<=z1;z++){let l='';for(let x=x0;x<=x1;x++){const k=K(x,z),t=landMap.get(k);l+=S.tiles[k]?'T':objAt(x,z)?'O':fixedAt(x,z)?'F':debrisAt(x,z)?'D':TOWN.path.has(k)?'P':t==='grass'?'g':t==='sand'?'s':t==='bridge'?'b':t==='river'?'r':t?t[0]:'.';}out.push(String(z).padStart(3)+' '+l);}return out.join('\n');},
    showcase:()=>loadShowcase(),
    // wild-island settling: the heart's spot, revive it, place a blueprint at a spot, finish tonight's building
    heartAt:()=>TOWN.plaza.slice(),revive:()=>{if(S.heartAt)return [S.heartAt.x,S.heartAt.z];startBlueprint('seed');if(!placing||placing.bp!=='seed')return null;const at=[placing.x,placing.z];bpPlace();return S.heartAt?at:null;},bp:(k,x,z)=>{startBlueprint(k);if(x!==undefined)bpMove(x,z);return placing&&bpOk(placing.x,placing.z)?[placing.x,placing.z]:null;},bpPlace:()=>{if(placing&&placing.bp)bpPlace();},goal:()=>{const g=nextGoal();return g&&g.name;},dawn:()=>{dawn(true);return S.day;},shoo:()=>{for(const n of npcs){n.x=n.b.door[0]+0.5;n.z=n.b.door[1]+0.3;n.path=null;n.state='idle';n.wait=30;n.act=null;}return npcs.length;},
    // place every earned kit wherever there's room (clearing a patch if it has to), finished at once
    buildAll:()=>{grantKits();for(const k of Object.keys(S.kits||{})){if(!S.kits[k])continue;let at=null;for(const [x,z] of islands[0].grass){if(farmQ(x,z)<1.3)continue;S.debris=S.debris.filter(d=>!(d.x>=x&&d.x<=x+1&&d.z>=z&&d.z<=z+2));if(bpOk(x,z)){at=[x,z];break;}}
      if(!at)continue;const t=k.startsWith('vh')?'vh':k;S.builds.push({t,n:t==='vh'?+k.slice(2):undefined,x:at[0],z:at[1],day:S.day-1});delete S.kits[k];rebuildHome();}syncDebris();morningMoveIn(true);return TOWN.bld.filter(b=>!b.locked).length;},paths:()=>TOWN.path.size,wild:()=>{const c={};for(const d of S.debris)c[d.k]=(c[d.k]||0)+1;return c;},
    // Island Heart: jump to a level (as if earned, without the card), and run a morning's move-in
    setLevel:n=>{S.xp=LV[n-1]||0;grantKits();rebuildHome();initNPCs();updateHUD();return level();},moveIn:()=>{morningMoveIn();return npcs.length;},
    next:()=>{const u=nextUnlock();return u&&u.name;},xp:n=>{addXP(n);return level();},plots:()=>TOWN.bld.map(b=>b.t+(b.t==='vh'?b.n:'')+(b.locked?':plot':'')),
    // every crop at one stage, rendered at the same scale on a patch of soil (data URLs), for eyeballing the models
    dock:()=>[DOCK.x,DOCK.z],openBush:()=>{const t=S.debris.filter(q=>q.k==='bush'&&!S.debris.some(d=>d.k==='tree'&&Math.abs(d.x-q.x)<=2&&Math.abs(d.z-q.z)<=3)).sort((a,b)=>Math.hypot(a.x-vil.x,a.z-vil.z)-Math.hypot(b.x-vil.x,b.z-vil.z))[0];return t&&[t.x,t.z];},nearDebris:k=>{const d=S.debris.filter(q=>q.k===k).sort((a,b)=>Math.hypot(a.x-vil.x,a.z-vil.z)-Math.hypot(b.x-vil.x,b.z-vil.z))[0];return d&&[d.x,d.z];},calm:()=>{forageOff=true;S.finds=S.finds.filter(f=>!forageOf(f));syncLife();for(const b of bugs)scene.remove(b.g);bugs.length=0;for(let i=critters.length-1;i>=0;i--)dropCritter(i);},homeAt:()=>S.homeAt&&[S.homeAt.x,S.homeAt.z],riverSpot:()=>{let best=null,bd=1e9;for(const [k] of riverSurf){const [x,z]=k.split(',').map(Number);if(islMap.get(k)!==0)continue;const d=Math.hypot(x-vil.x,z-vil.z);if(d<bd){bd=d;best=[x,z];}}return best;},noBugs:()=>{flushT=40;/* and nothing flushed out for a while */for(const b of bugs)scene.remove(b.g);bugs.length=0;for(let i=critters.length-1;i>=0;i--)dropCritter(i);},
    findList:()=>{const o={};for(const f of S.finds)o[f.k]=(o[f.k]||0)+1;return o;},
    goNearFind:k=>{const f=S.finds.filter(q=>q.k===k).sort((a,b)=>Math.hypot(a.x-vil.x,a.z-vil.z)-Math.hypot(b.x-vil.x,b.z-vil.z))[0];if(!f)return null;
      const sp=[[2,0],[-2,0],[0,2],[0,-2],[2,2],[-2,2]].map(([a,b])=>[f.x+a,f.z+b]).find(([a,b])=>walkable(a,b))||[f.x,f.z+1];vil.x=vil.tx=sp[0];vil.z=vil.tz=sp[1];vil.path=null;cam.tx=vil.x;cam.tz=vil.z;return[f.x,f.z];},
    goNearTree:()=>{const d=S.debris.filter(q=>q.k==='tree').sort((a,b)=>Math.hypot(a.x-vil.x,a.z-vil.z)-Math.hypot(b.x-vil.x,b.z-vil.z))[0];const sp=[[2,0],[-2,0],[0,2],[0,-2]].map(([a,b])=>[d.x+a,d.z+b]).find(([a,b])=>walkable(a,b));
      vil.x=vil.tx=sp[0];vil.z=vil.tz=sp[1];vil.path=null;cam.tx=vil.x;cam.tz=vil.z;return[d.x,d.z];},
    screenOf:(x,z,h=0.1)=>{const s=toScreen(x,topY(x,z)+h,z);return[s[0],s[1]];},invCount:()=>Object.values(S.inv).reduce((a,b)=>a+b,0),shookN:()=>Object.keys(S.shook||{}).length,
    ripeNear:(t='pumpkin')=>{const x=Math.round(vil.x)+1,z=Math.round(vil.z),k=K(x,z);S.debris=S.debris.filter(d=>!(d.x===x&&d.z===z));syncDebris();S.tiles[k]={w:1,crop:{t,p:1,v:'normal',m:0}};syncCrop(k);return[x,z];},
    harvestAt:(x,z)=>{harvest(K(x,z),x,z);},
    // a butterfly a couple of tiles from you; bugAt gives its screen position and how many bugs you've caught
    bugNear:()=>{const isl=curIsl(),id=Object.keys(BUGS).find(k=>BUGS[k].kind!=='crawl'&&BUGS[k].time!=='night'&&BUGS[k].bio.includes(isl.biome));const g=bugGroup(BUGS[id]);g.scale.setScalar(BUG_SCALE);scene.add(g);
      const hx=Math.round(vil.x)+2,hz=Math.round(vil.z)+1;g.position.set(hx,topY(hx,hz)+0.4,hz);bugs.push({id,g,hx,hz,t:0,life:999,ph:0,out:0,isl:isl.id,crawl:false,still:true});return id;},
    bugAt:()=>{const b=bugs[bugs.length-1];const caught=Object.keys(S.alm).filter(k=>k.startsWith('b:')).length;if(!b)return{caught};const s=toScreen(b.g.position.x,b.g.position.y,b.g.position.z);return{x:s[0],y:s[1],n:bugs.length,caught,tool:S.tool};},
    camInfo:()=>({dist:cam.dist,pitch:cam.pitch,fov:camera.fov,pos:camera.position.toArray(),W,H,PX,hy:skyMat.uniforms.hy.value}),
    critters:()=>{const o={};for(const c of critters){o[c.k]=(o[c.k]||0)+1;if(!isFinite(c.g.position.x+c.g.position.y+c.g.rotation.x+c.g.rotation.y))o.bad=(o.bad||0)+1;}return o;},spawnCritter:k=>spawnCritter(k),vilAt:()=>[vil.x,vil.z],critClear:()=>{for(let i=critters.length-1;i>=0;i--)dropCritter(i);},walkTest:()=>{const t=S.debris.filter(d=>d.k==='tree').sort((a,b)=>Math.hypot(a.x-vil.x,a.z-vil.z)-Math.hypot(b.x-vil.x,b.z-vil.z))[0];if(!t)return null;vil.x=vil.tx=t.x-2;vil.z=vil.tz=t.z;vil.path=null;goTo(t.x+2,t.z);return [t.x,t.z];},vilPos:()=>[vil.x,vil.z,vil.tx,vil.tz,vil.path&&vil.path.length],solidAt:(x,z)=>solidR(x,z),setShells:n=>{S.shells=n;updateHUD();},terraTest:(mode,x,z)=>{const t0=performance.now();const sh=S.shells;terraApply([[x,z]],mode);return{ms:Math.round(performance.now()-t0),lvl:lvlMap.get(K(x,z))||0,type:landMap.get(K(x,z)),paid:sh-S.shells,terra:S.terra&&S.terra[K(x,z)]};},
    terraPlan:(mode,x,z)=>terraPlan(x,z,mode),coastGrass:()=>{const isl=islands[0];return isl.grass.filter(([x,z])=>!(lvlMap.get(K(x,z)))&&freeTile(x,z)&&!TOWN.path.has(K(x,z))&&[[1,0],[-1,0],[0,1],[0,-1]].some(([a,b])=>isSeaT(landMap.get(K(x+a,z+b))))).sort((a,b)=>Math.hypot(a[0]-vil.x,a[1]-vil.z)-Math.hypot(b[0]-vil.x,b[1]-vil.z))[0]||null;},
    freeGrass:()=>{const isl=islands[0];return isl.grass.filter(([x,z])=>freeTile(x,z)&&!S.tiles[K(x,z)]).sort((a,b)=>Math.hypot(a[0]-vil.x,a[1]-vil.z)-Math.hypot(b[0]-vil.x,b[1]-vil.z))[1]||null;},
    swimRec:on=>{if(on){swim.rec=[];return 0;}const r=swim.rec;swim.rec=null;return r;},sceneToon:()=>{const out={};for(const o of scene.children){if(!o.visible)continue;let n=0;o.traverseVisible(q=>{if(q.isMesh)n++;});if(!n)continue;const nm=o===debrisRoot?'debris':o===lifeRoot?'life':o===objRoot?'objs':o===cropRoot?'crops':(typeof cropRoot!=='undefined'&&o===cropRoot)?'crops':o===villager?'player':islands.some(i=>i.group===o)?'isl'+islands.findIndex(i=>i.group===o):npcs.some(q=>q.g===o)?'npc':'';const k=nm+(o.name||o.type)+(o.isGroup?'['+o.children.length+']':'')+':'+(o.material?o.material.type:'')+(o.geometry?'/'+(o.geometry.type):'');out[k]=(out[k]||0)+n;}return Object.entries(out).sort((a,b)=>b[1]-a[1]).slice(0,25);},plantThumbs:(size=160)=>POT_PLANTS.map(([k,n])=>[n,snapThumb(objGroup('pot_'+k,3,0),size)]),instList:()=>{const out=[];islands[0].group.traverseVisible(o=>{if(!o.isInstancedMesh)return;const g=o.geometry,n=(g.index?g.index.count:g.attributes.position.count)/3;out.push([o.material.type+(o===islands[0].gIM?'(grass)':FLORA_GEOS.includes(o.geometry)?'(flora'+FLORA_GEOS.indexOf(o.geometry)+')':FLORA_LO.includes(o.geometry)?'(floraLo)':o.geometry===CLOVER_GEO?'(clover)':o.geometry===PEBBLE_GEO?'(pebble)':''),Math.round(n),o.count,Math.round(n*o.count)]);});return out.sort((a,b)=>b[3]-a[3]).slice(0,12);},reefMs:()=>{const t=performance.now(),g=reefGen();let mx=0,n=0;for(;;){const a=performance.now(),r=g.next();mx=Math.max(mx,performance.now()-a);(window.__st=window.__st||[]).push(Math.round(performance.now()-a));n++;if(r.done)break;}const st=window.__st;window.__st=null;return{total:Math.round(performance.now()-t),longestStep:Math.round(mx),steps:n,st:st.join(" ")};},swimSpot:()=>{if(!reef||reefDirty)buildReef();const isl=islands[0];let best=null,bd=1e9;for(const [x,z] of isl.sand){if(Math.abs(x-DOCK.x)<4&&Math.abs(z-DOCK.z)<9)continue;for(const [dx,dz] of [[0,1],[1,0],[-1,0],[0,-1]]){const tx=x+dx*5,tz=z+dz*5;if(!swimmable(tx,tz)||!canDive(tx,tz)||isLand(x+dx,z+dz))continue;const sc=Math.abs(x-DOCK.x)+Math.abs(z-DOCK.z);if(sc<bd){bd=sc;best=[x,z,tx,tz];}}}return best;},
    swimState:()=>({under:!!swim.under,look:+(swim.look||0).toFixed(2),on:swim.on,depth:+swim.depth.toFixed(2),breath:+swim.breath.toFixed(2),uw:+swim.uw.toFixed(2),y:+vil.y.toFixed(2),x:+vil.x.toFixed(2),z:+vil.z.toFixed(2),reefD:+reefD(vil.x,vil.z).toFixed(2),R:+reefR().toFixed(2),life:seaLife.map(c=>c.k),tide:+tideK().toFixed(2),canDive:canDive(vil.x,vil.z)}),
    dive:on=>{if(on){if(divePress()){swim.hold=true;swim.up=false;}}else swim.hold=false;},rise:()=>surfaceNow(),swimTo:(x,z)=>swimTo(x,z),setBreath:b=>{swim.breath=b;},
    seaSpawn:(k,fw=2,rt=0,up=0.2)=>{const E=SEA[k],g=seaModel(k);scene.add(g);const sy=Math.sin(cam.yaw),cy=Math.cos(cam.yaw),x=vil.x-sy*fw+cy*rt,z=vil.z-cy*fw-sy*rt,y=E.zone==='floor'?seabedY(x,z)+0.04:vil.y+up;const c={k,E,g,cx:x,cz:z,x,z,y,y0:y,sc:SEA_TIERS[E.tier].sc,rad:0.3,ang:0,dir:1,sp:0.05,ph:0,t:5,out:0,life:999};seaLife.push(c);return seaLife.length;},
    seaTick:()=>{try{updateReefLife(0.016,1);return 'ok';}catch(e){return e.message+' '+e.stack.slice(0,300);}},seaScreen:k=>{const c=seaLife.find(q=>q.k===k);if(!c)return null;const s=toScreen(c.x,c.y+0.1,c.z);return[s[0],s[1],+Math.hypot(c.x-vil.x,c.z-vil.z).toFixed(2)];},toScreenW:(x,y,z)=>toScreen(x,y,z),reefAt:h=>{const o=S.hour;DS.hour(h);updateTides();const r={h,tide:+tideK().toFixed(2),R:+reefR().toFixed(2),can:Object.keys(SEA).filter(k=>seaOk(SEA[k]))};DS.hour(o);updateTides();return r;},alm:k=>S.alm[k]||0,terraAt:(x,z)=>[S.terra&&S.terra[K(x,z)],lvlMap.get(K(x,z))||0,landMap.get(K(x,z))],equipT:k=>equip(k),camY:()=>[+camera.position.y.toFixed(2),+tideY.toFixed(2),+cam.pitch.toFixed(2)],riverTile:()=>{let b=null,bd=1e9;for(const [k,t] of landMap){if(t!=='river'||islMap.get(k)!==0||S.terra&&S.terra[k]!==undefined)continue;const [x,z]=k.split(',').map(Number);if(landMap.get(K(x+1,z))==='bridge'||landMap.get(K(x-1,z))==='bridge')continue;const d=Math.hypot(x-vil.x,z-vil.z);if(d<bd){bd=d;b=[x,z];}}return b;},seaAlm:ks=>{for(const k of ks)S.alm['s:'+k]=1;},seaDump:()=>seaLife.map(c=>[c.k,+c.x.toFixed(2),+c.y.toFixed(2),+c.z.toFixed(2),c.g.visible,c.g.parent===scene,c.g.children.length,+c.g.scale.x.toFixed(2),c.out]),seaCatch:()=>{const c=seaLife.slice().sort((a,b)=>Math.hypot(a.x-vil.x,a.z-vil.z)-Math.hypot(b.x-vil.x,b.z-vil.z))[0];if(!c)return null;catchSeaLife(c);return c.k;},
    tideSet:h=>{const t0=tideNow();S.toff=(S.toff||0);/* move the clock so the tide is high (1) or low (0) */return tideAt(t0);},spGallery:(sea,size=140)=>{const o=S.seasonOv;S.seasonOv=sea||o;const out=[];for(let sp=0;sp<TREE_NS;sp++)for(let sh=0;sh<TREE_SP[sp].shapes;sh++){const v=sp+sh*TREE_NS,w=new T.Group(),t=new T.Mesh(merge(wildTreeParts(v)),leafMat);w.add(t);
      const fp=fruitParts(v);if(fp.length&&fruitSeason(v))w.add(new T.Mesh(merge(fp),fruitMat));w.add(M([P(BOX,0x6aa843,0,-0.03,0,0,0,0,1.6,0.06,1.6)]));out.push([TREE_SP[sp].name+(sh?' ii':''),snapThumb(w,size)]);}S.seasonOv=o;return out;},
    fruitShow:k=>{const w=new T.Group();w.add(M(fruitModel(k,mulberry(3))));return snapThumb(w,120);},
    fruitList:sp=>S.debris.filter(d=>d.k==='tree'&&fruitOn(d)&&treeSp(d.v).id===sp).sort((a,b)=>Math.hypot(a.x-vil.x,a.z-vil.z)-Math.hypot(b.x-vil.x,b.z-vil.z)).map(d=>[d.x,d.z]),shakeAt:(x,z)=>{const t=debrisAt(x,z);if(t)shakeTree(t);return !!t;},shakeNear:()=>{const t=S.debris.filter(d=>d.k==='tree'&&fruitOn(d)).sort((a,b)=>Math.hypot(a.x-vil.x,a.z-vil.z)-Math.hypot(b.x-vil.x,b.z-vil.z))[0];if(!t)return null;shakeTree(t);return [t.x,t.z,treeSp(t.v).id];},
    fruitTrees:()=>S.debris.filter(d=>d.k==='tree'&&fruitOn(d)).length,species:()=>{const o={};for(const d of S.debris)if(d.k==='tree'){const n=treeSp(d.v).id;o[n]=(o[n]||0)+1;}return o;},critStrip:(k,beh,st,times,size=150)=>times.map(sec=>{const g=critModel(k,1),c={k,v:1,g,x:0,z:0,y:0,state:st||'idle',t:0,wait:99,tx:40,tz:0,hx:40,hz:0,ph:0,fx:1,fz:0,hw:0,hp:0,out:0};if(beh){c.beh=beh;c.bt=99;}
      let hs=[0,1];for(let t=0;t<sec;t+=1/60){c.t+=1/60;hs=rigCritter(c,1/60,t);if(c.state==='gone')break;}g.position.set(0,hs[0],0);g.scale.set(1,hs[1],1);g.rotation.y=2.36;
      const w=new T.Group();w.add(g);w.add(M([P(BOX,0x6aa843,0,-0.03,0,0,0,0,k==='deer'?1.6:0.8,0.06,k==='deer'?1.6:0.8)]));return snapThumb(w,size);}),critShow:(k,x,z,beh,st)=>{for(const q in CRIT)CRIT[q].flee=0;const c=critterAt(k,x,z,false);c.t=2;c.wait=99;if(beh){c.beh=beh;c.bt=99;}if(st==='move'){c.tx=x+40;c.tz=z;c.state='move';c.hx=x+40;}if(st==='flee'){c.fx=1;c.fz=0;c.state='flee';c.t=0.5;c.hw=0;}c.g.rotation.y=1.2;return critters.length-1;},
    treeGallery:(size=200)=>{const out=[],so=S.seasonOv;const add=(name,parts,sm)=>{const w=new T.Group();w.add(M(parts));const box=new T.Mesh(sm?new T.BoxGeometry(1.3,1.3,1.3):new T.BoxGeometry(2.4,3.4,2.4));box.position.y=sm?0.5:1.5;box.visible=false;w.add(box);w.add(M([P(BOX,0x6aa843,0,-0.03,0,0,0,0,2,0.06,2)]));out.push([name,snapThumb(w,size)]);};
      for(const k of ['oak','pine','maple','cherry','bush','snowpine'])add(k,treeParts(k,mulberry(7),0x9a9ea8));
      for(const se of ['spring','summer','autumn','winter']){S.seasonOv=se;for(const v of [0,2,3])add(se+' '+v,wildTreeParts(v));}
      for(const lv of [1,2,4,7,11]){const q=seedTreeParts(lv);add('heart '+lv,[...q.tp,...q.p,...q.gl]);}
      for(const se of ['spring','summer','autumn','winter']){S.seasonOv=se;for(const v of [0,1,2])add('bush '+se+' '+v,bushParts(v),1);}
      for(const v of [0,1,2])add('weed '+v,debrisParts('weed',mulberry(3+v),v),1);add('rock',debrisParts('rock',mulberry(3)),1);add('boulder',debrisParts('boulder',mulberry(4)),1);S.seasonOv=so;return out;},
    critGallery:(size=160)=>Object.keys(CRIT).map(k=>{const g=critModel(k,1),w=new T.Group();w.add(g);w.add(M([P(BOX,0x6aa843,0,-0.03,0,0,0,0,1.4,0.06,1.4)]));const s=k==='deer'?1.3:0.6,box=new T.Mesh(new T.BoxGeometry(s,s,s));box.position.y=s/2;box.visible=false;w.add(box);g.rotation.y=0.6;return [k,snapThumb(w,size)];}),
    cropGallery:(stage=3,size=160)=>CROP_IDS.map((id,i)=>{const c=cropParts(id,stage,i*97+5),g=new T.Group();if(c.leaf.length)g.add(M(c.leaf));if(c.fruit.length)g.add(M(c.fruit));g.scale.setScalar(0.95);
      const w=new T.Group();w.add(g);w.add(M([P(BOX,0x5e3c2a,0,-0.03,0,0,0,0,1,0.06,1)]));const box=new T.Mesh(new T.BoxGeometry(1.1,1.5,1.1));box.position.y=0.7;box.visible=false;w.add(box);return [id,snapThumb(w,size)];}),
    ripen:()=>{for(const k in S.tiles){const t=S.tiles[k];if(t.crop)t.crop.p=1;}syncAllCrops();},
    line:()=>({vis:fishLine.visible,p:[...linePts].slice(0,6).concat([...linePts].slice(-3)).map(v=>+v.toFixed(2)),bob:bobber.position.toArray().map(v=>+v.toFixed(2)),st:fishing&&fishing.state}),
    fishShore:()=>{const isl=curIsl();for(const [x,z] of isl.sand)for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){let ok=true;for(let r=1;r<=4;r++)if(isLand(x+dx*r,z+dz*r))ok=false;if(!ok)continue;DS.tp(x,z);startFishing(x+dx*3,z+dz*3);return[x,z,dx,dz];}return null;},
    fish:()=>{const isl=curIsl();if(!isl)return false;const [x,z]=isl.sand[0];DS.tp(x,z);startFishing(x+3,z+3);return !!fishing;},
    fastTravel:id=>fastTravel(islands[id]),
    npcRouteOnLand:()=>{updateNpcBoat(0,0);const R=npcRoute;if(!R.pts)return -1;let n=0;for(let d=0;d<R.total;d+=0.25){R.d=d;updateNpcBoat(0,0);if(seaBlocked(Math.round(npcBoat.position.x),Math.round(npcBoat.position.z)))n++;}return n;},
    sailTo:id=>{const isl=islands[id];if(!S.sea){S.sea=true;const b=S.boat;vil.x=b.x;vil.z=b.z;}sailToIsland(isl);return !!sail;},
    pick:(cx,cy)=>pick(cx,cy),heart:id=>islands[id].heart,giveSeeds:n=>{S.inv['g:driftseed']=(S.inv['g:driftseed']||0)+n;},plantHeart:id=>{plantDriftseed(islands[id]);return stageOf2(islands[id]);},tide:()=>({tideY,lowTide,finds:S.finds.filter(f=>f.tide).length}),beam:()=>({has:!!beam,vis:beam&&beam.visible,op:beamMat.opacity,nightF,parentOk:beam&&beam.parent===islands[0].group,pos:beam&&beam.position.toArray(),grpVis:islands[0].group.visible}),spots:()=>({cafe:(TOWN.bld.find(b=>b.t==='cafe')||{}).x!==undefined?[TOWN.bld.find(b=>b.t==='cafe').x,TOWN.bld.find(b=>b.t==='cafe').z]:null,light:TOWN.light&&[TOWN.light.x,TOWN.light.z],shop:(b=>b&&[b.x,b.z])(TOWN.bld.find(b=>b.t==='shop'))}),view:(x,z,yaw,dist,pitch)=>{introCam=null;S.sea=false;vil.x=vil.tx=x;vil.z=vil.tz=z;vil.path=null;cam.tx=x;cam.tz=z;cam.yaw=yaw;cam.dist=dist;if(pitch)cam.pitch=pitch;},homes:()=>TOWN.bld.filter(b=>b.t==='vh').map(b=>[b.x,b.z,planVillagers()[b.n%6].pers]),plaza:()=>TOWN.plaza.slice(),lineup:(list)=>{const g=new T.Group();g.name='lineup';(list||Object.keys(SPECIES)).forEach((sp,i)=>{const L=Object.keys(STYLE),pe=L[i%L.length],st=STYLE[pe];const m=npcModel(sp,SPECIES[sp].col[0],[0x6ab8a8,0x5a8ae0,0xe8866a,0xd8b84a,0xf39ab0,0x9a8ad8][i%6],st.a[i%st.a.length],st.o[i%st.o.length]);const x=vil.x-3+(i%7)*1.0,z=vil.z-1-Math.floor(i/7)*1.4;m.position.set(x,surfY(x,z),z);g.add(m);});scene.add(g);return (list||Object.keys(SPECIES)).length;},npcAt:i=>{const n=npcs[i];return[n.x,n.z];},bldAt:t=>{const b=TOWN.bld.find(q=>q.t===t);return b?[b.x,b.z]:null;},calls:()=>{const out={};const names=new Map([[debrisRoot,'debris'],[lifeRoot,'life']]);try{names.set(cropRoot,'crops');}catch(e){}try{names.set(objRoot,'objs');}catch(e){}
      scene.traverseVisible(o=>{if(!(o.isMesh||o.isPoints||o.isLine))return;let p=o,k=null;while(p&&p!==scene){if(names.has(p)){k=names.get(p);break;}const ii=islands.findIndex(i=>i.group===p||i.pgroup===p);if(ii>=0){k=ii===0?'home':'isl';break;}if(npcs.some(n=>n.g===p)){k='npc';break;}if(p===villager){k='player';break;}p=p.parent;}
        k=k||('scene:'+(o.name||o.type)+':'+(o.material&&o.material.type));out[k]=(out[k]||0)+1;});return Object.entries(out).sort((a,b)=>b[1]-a[1]).slice(0,20).map(x=>x.join(' '));},tris:()=>{const out={};const tag=o=>{let p=o;while(p){if(p.userData&&p.userData.tag)return p.userData.tag;if(islands.some(i=>i.group===p))return 'isl'+islands.findIndex(i=>i.group===p)+':'+(o.isInstancedMesh?'inst':'mesh');if(p===scene)break;p=p.parent;}return (o.isInstancedMesh?'inst:':'mesh:')+(o.material&&o.material.type)+(o.parent===scene?'@scene':'');};
      scene.traverseVisible(o=>{if(!(o.isMesh||o.isInstancedMesh||o.isPoints))return;const g=o.geometry;if(!g)return;const n=(g.index?g.index.count:g.attributes.position.count)/3*(o.isInstancedMesh?o.count:1);const k=tag(o);out[k]=out[k]||{tris:0,n:0,shadow:0};out[k].tris+=n;out[k].n++;if(o.castShadow)out[k].shadow+=n;});
      return Object.entries(out).sort((a,b)=>b[1].tris-a[1].tris).slice(0,25).map(([k,v])=>k+' '+Math.round(v.tris)+' ('+v.n+' objs, shadow '+Math.round(v.shadow)+')');},floraSpot:()=>{let best=null,bn=0;const ks=[...TOWN.flora.keys()].filter(k=>!S.tiles[k]&&!(TOWN.fHid&&TOWN.fHid.get(k))).map(k=>k.split(',').map(Number)).filter(([x,z])=>!S.objs.some(o=>Math.abs(o.x-x)<2&&Math.abs(o.z-z)<2)&&!Object.keys(S.tiles).some(q=>{const [a,c]=q.split(',').map(Number);return Math.abs(a-x)<3&&Math.abs(c-z)<3;}));for(const [x,z] of ks){let n=0;for(const [a,c] of ks)if(Math.abs(a-x)<=2&&Math.abs(c-z)<=2)n++;if(n>bn){bn=n;best=[x,z];}}return [best,bn];},plaza:()=>TOWN.plaza,lights:()=>({hour:S.hour,nightF,rain:rainMix,hemi:[hemi.intensity,hemi.color.getHexString(),hemi.groundColor.getHexString()],sun:[sun.intensity,sun.color.getHexString()],fire:[fireLight.intensity,fireLight.distance,fireLight.decay],rim:[...RIM],bloomC:postMat.uniforms.bloomC.value.toArray(),th:brightMat.uniforms.th.value,gw:postMat.uniforms.gw.value,pool:firePoolMat.opacity,lights:(()=>{const o=[];scene.traverse(q=>{if(q.isLight)o.push(q.type+':'+(+q.intensity).toFixed(2)+(q.visible?'':'(hidden)'));});return o;})()}),meadow:(yaw=0.5,len=10)=>{const ok=k=>!(TOWN.fHid&&TOWN.fHid.get(k));const ks=[...TOWN.flora.keys()].filter(ok).map(k=>k.split(',').map(Number));const sx=Math.sin(yaw),sz=Math.cos(yaw);let best=null,bs=-1;
      for(const [x,z] of ks){let n=0;for(const [a,c] of ks)if(Math.hypot(a-x,c-z)<=3)n++;if(n<=bs)continue;let clear=true;for(let t=-1;t<=len&&clear;t++)for(let w=-1;w<=1;w++){const qx=Math.round(x+sx*t+sz*w),qz=Math.round(z+sz*t-sx*w);if(solidR(qx,qz)>0){clear=false;break;}}if(clear){bs=n;best=[x,z];}}return [best,bs];},floraThumbs:(sz=160,lo)=>(lo?FLORA_LO:FLORA_GEOS).map((g,i)=>[FLORA_KEYS[i],snapThumb((()=>{const m=new T.InstancedMesh(g,flowerMat,1);m.setMatrixAt(0,new T.Matrix4());return m;})(),sz),(g.attributes.position.count/3)|0]),
    perf:()=>({...FRAME_STAT,shadowCasters:(()=>{let n=0;scene.traverseVisible(o=>{if((o.isMesh||o.isInstancedMesh)&&o.castShadow)n++;});return n;})()}),zoom:d=>{cam.dist=d;},collectAll:()=>{for(const k in FISH)S.alm['f:'+k]=1;for(const k in BUGS)S.alm['b:'+k]=1;refreshMuseumShow();},enterMuseum:()=>enterHouse('museum',TOWN.bld.find(b=>b.t==='museum'),null),museumDoor:()=>{const b=TOWN.bld.find(q=>q.t==='museum');return b.door;},roomGo:(x,z)=>{inside.tx=x;inside.tz=z;},look:(sp,fur,shirt)=>{setLook(Object.assign({sp},fur?{fur}:{},shirt?{shirt}:{}));return S.look;},beach:id=>{const i=islands[id],s=i.sand.filter(([x,z])=>{const c=SAND_CH.get(K(x,z));return c&&Math.min(...c)<0.1;});return s[Math.floor(s.length/3)]||i.sand[0];},tool:k=>{equip(k);return S.tool;},tile:(x,z)=>S.tiles[K(x,z)]||null,vil:()=>({x:vil.x,z:vil.z}),
    boat:()=>({x:S.boat.x,z:S.boat.z,onLand:seaBlocked(Math.round(S.boat.x),Math.round(S.boat.z)),sailing:!!sail}),
  };
  console.info('Driftseed debug API ready: window.DS');
}
